node.js의 app을 nginx에 연결했던 것처럼 Flask에 연결하니 api는 잘 작동했지만 swagger에서 오류가 났다. 포트를 직접 넣어서 nginx의 리버스 프록시를
이용하지 않고는 전부다 정상적으로 작동되는 것으로보아 nginx의 설정을 의심했다.

```
No API definition provided.
```

swaggerui에 들어가면 위와 같은 메시지가 뜨고 화면이 표시가 안됨.

확인결과 ui를 그릴 때, swagger.json을 기반으로 가져오는데 이 swagger.json이 nginx에서 정상적으로 보이는데, flask-restplus 내부에서 불러올때 url을
\http\://xx.xx.xx.xx/swagger.json 처럼 `\`가 포함되면서 생긴 오류였다.

```
upstream flask-app {
        server                  127.0.0.1:5000;
}
  
server {
        listen                  80;
        server_name             127.0.0.1;
        
        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;
    
        location / {
                proxy_set_header        Host \$host:\$server_port;
                proxy_set_header        X-Real-IP \$remote_addr;
                proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto \$scheme;
  
                proxy_pass              http://flask-app;
        }
}
```

위의 설정이 node app에서는 잘 작동됬지만 flask에서는 문제가 있는 것 같아서 수정했다.

```
upstream keras-app {
        server                  127.0.0.1:5000;
}
  
server {
        listen                  80;
        server_name             127.0.0.1;
        
        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;
    
        location / {
                proxy_set_header        Host              $host;
                proxy_set_header        X-Real-IP         $remote_addr;
                proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
  
                proxy_pass              http://keras-app;
        }
}
```

swagger문서가 정상적으로 페이지에 그려진다.

gunicorn에서 gevent를 사용하려고 했는데 swaggerui가 빈 페이지로 뜨는 오류가 발생하였다. 그리고 gunicorn의 gevent가 제대로 적용이 되지 않는 것 같아서 github에서 찾아보니 관련 issuse가 있었고 gunicorn의 버전을 최신버전인 20.0.4로 업데이트하였더니 문제가 해결되었다.
