### 20200217
---

크롤러가 오류가 발생해서 확인한 결과 아래와 같은 오류를 내고 있었다.

```
HTTPSConnectionPool(host='www.sample.co.kr', port=443): Max retries exceeded with url: /sample/board/view?id=1111&page=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
```

사이트를 확인해보니 HTTPS가 적용된 것 같았고, HTTPS가 적용된 사이트에 request를 하면서 오류가 발생한 것이다.

```python
res = requests.get(url)
root = lxml.html.fromstring(res.text)
```

이렇게 request로만 요청하던 것을 아래처럼 바꾸어주었다.

```python
context = ssl._create_unverified_context()
res = urllib.request.urlopen(url, context=context).read()
root = lxml.html.fromstring(res.decode('UTF-8'))
```

이제 오류가 발생하지 않고 https로 요청을 보내고 수집해오는 것을 확인할 수 있다.

혹시 BeautifulSoup를 사용한다면 아래처럼 변경할 수 있다.

```python
res = urllib.request.urlopen(url, context=context).read()
html = res.decode("UTF-8")
soup = bs(html, 'html.parser')
```

request를 사용했을 때는 요청한 이후에 `.text`를 하고 `bs html parser`를 사용했지만 `context`를 이용해서 `urllib.request.urlopen`를 할 사용할 때는 decode를 사용해서 파싱 하면 된다.