### 20191223
---

pytest를 사용해서 테스트 코드를 작성하는데 발생한 오류와 해결법이다.

```python
from app.test.fixtures import app, client
from .service import SampleService # 오류 발생!

def test_service_works():
    # ...
```

SampleService는 실제로는 잘 작동하고 있었다. 하지만 테스트 코드를 작성하려고 하면 오류가 발생했다.

```
Traceback:
app\api\sample\service_test.py:3: in <module>
    from .service import SampleService
app\api\sample\service.py:7: in <module>
    from app import graph, sess, trainer
E   ImportError: cannot import name 'graph' from 'app'
```

service에서 일반 flask app에서 tensorflow로 학습한 모델을 테스트 코드에서 사용하는데 오류가 난다고 생각했다.

flask의 init을 테스트 할 때, app과 client를 fixture를 사용해서 관리해서 테스트를 하고 있었다.
controller에서 api에 대한 end to end 테스트를 할 때도, fixture 객체로 선언한 client를 사용했었다.

테스트로 사용하고 있는 app context를 사용하도록 명시적으로 해주어야 겠다고 생각했다.
`app_context()` 메서드를 사용해서 테스트에서 사용하는 컨텍스트를 명시적으로 생성해주었다.

> 결론은 테스트 할 때는 코드가 올바른 전역 변수를 찾을 수 있도록 "응용 프로그램 컨텍스트"를 직접 설정해야한다는 것이다.

아래는 개선된 코드이다.

```python
from pytest import fixture
from app.test.fixtures import app, client


@fixture
def app_context(app):
    with app.app_context():
        yield


def test_service_works(app_context):
    from .service import SampleService # 기존에 오류가 났던 부분

    # ...
```

SampleService를 import해서 사용하는데 문제가 없이 넘어갔다. SampleService의 코드를 테스트 할 수 있게 되었다.

```
============================================================================================ test session starts ============================================================================================
platform win32 -- Python 3.7.4, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: C:\Dev\sample-rest-api
collected 7 items                                                                                                                                                                                            

app\__init__test.py ..                                                                                                                                                                                 [ 28%]
app\api\sample\controller_test.py ..                                                                                                                                                                   [ 57%]
app\api\sample\schema_test.py ..                                                                                                                                                                       [ 85%]
app\api\sample\service_test.py .                                                                                                                                                                       [100%]

====================================================================================== 7 passed, 21 warnings in 15.02s ======================================================================================
```

---
#### 참고

https://stackoverflow.com/questions/31444036/runtimeerror-working-outside-of-application-context

https://blog.outsider.ne.kr/1350